CREATE TABLE `coffeebreak_test`.`T_ADDRESS` (
  `F_ADDRESS_ID` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `F_STREET` VARCHAR(100) NOT NULL,
  `F_HOUSE` INT(11) NOT NULL,
  `F_APARTMENT` INT(11) NOT NULL,
  `F_CUSTOMER_ID` BIGINT(12) NOT NULL,
  PRIMARY KEY (`F_ADDRESS_ID`)
)DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `coffeebreak_test`.`T_CUSTOMER` (
  `F_CUSTOMER_ID` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `F_FIRST_NAME` VARCHAR(100) NOT NULL,
  `F_LAST_NAME` VARCHAR(100) NOT NULL,
  `F_LOGIN` VARCHAR(45) NOT NULL,
  `F_PASSWORD` VARCHAR(255) NOT NULL,
  `F_ROLE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`F_CUSTOMER_ID`),
  UNIQUE INDEX `F_CUSTOMER_ID_UNIQUE` (`F_CUSTOMER_ID` ASC)
)DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `coffeebreak_test`.`T_COFFEE_CUP` (
  `F_COFFEE_CUP_ID` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `F_COFFEE_ID` BIGINT(12) NOT NULL,
  `F_ORDER_ID` BIGINT(12) NOT NULL,
  PRIMARY KEY (`F_COFFEE_CUP_ID`)
)DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `coffeebreak_test`.`T_ORDER` (
  `F_ORDER_ID` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `F_ORDER_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `F_TOTAL_PRICE` DOUBLE NOT NULL,
  `F_CUSTOMER_ID` BIGINT(12) NOT NULL,
  PRIMARY KEY (`F_ORDER_ID`),
  UNIQUE INDEX `F_ORDER_ID_UNIQUE` (`F_ORDER_ID` ASC)
)DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `coffeebreak_test`.`T_COFFEE` (
  `F_COFFEE_ID` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `F_SORT` VARCHAR(120) NOT NULL,
  `F_DESCRIPTION` VARCHAR(150) NULL,
  `F_COST` DOUBLE NULL DEFAULT '0.0',
  PRIMARY KEY (`F_COFFEE_ID`)
)DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `coffeebreak_test`.`T_SAIL` (
  `F_ID` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `F_FREE_CUP` INT NOT NULL,
  `F_FREE_DELIVERY` DOUBLE NOT NULL,
  `F_DELIVERY` DOUBLE NOT NULL,
  PRIMARY KEY (`F_ID`)
)DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;